import { Button } from "@/components/ui/button";
import { Download } from "lucide-react";
import { useToast } from "@/hooks/use-toast";

interface ExportPDFProps {
  result: any;
  text: string;
}

export const ExportPDF = ({ result, text }: ExportPDFProps) => {
  const { toast } = useToast();

  const exportToPDF = () => {
    // Create HTML content for PDF
    const htmlContent = `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="UTF-8">
        <title>Analysis Report</title>
        <style>
          body { font-family: Arial, sans-serif; padding: 40px; max-width: 800px; margin: 0 auto; }
          h1 { color: #1a1a1a; border-bottom: 3px solid #4f46e5; padding-bottom: 10px; }
          h2 { color: #4f46e5; margin-top: 30px; }
          .header { background: #f3f4f6; padding: 20px; border-radius: 8px; margin-bottom: 30px; }
          .safe { color: #16a34a; font-weight: bold; }
          .harmful { color: #dc2626; font-weight: bold; }
          .category { padding: 10px; margin: 10px 0; border-left: 4px solid #4f46e5; background: #f9fafb; }
          .metric { display: inline-block; margin: 10px 20px 10px 0; }
          .label { font-weight: bold; color: #6b7280; }
          table { width: 100%; border-collapse: collapse; margin: 20px 0; }
          th, td { padding: 12px; text-align: left; border-bottom: 1px solid #e5e7eb; }
          th { background: #f3f4f6; font-weight: bold; }
          .footer { margin-top: 40px; padding-top: 20px; border-top: 2px solid #e5e7eb; font-size: 12px; color: #6b7280; }
        </style>
      </head>
      <body>
        <h1>Content Safety Analysis Report</h1>
        
        <div class="header">
          <p><strong>Generated:</strong> ${new Date().toLocaleString()}</p>
          <p><strong>Model:</strong> ${result.modelInfo?.name || 'BiLSTM + SAM + CFCLF'}</p>
          <p><strong>Accuracy:</strong> ${result.modelInfo?.accuracy || '94%'}</p>
        </div>

        <h2>Analyzed Content</h2>
        <p style="background: #f9fafb; padding: 15px; border-radius: 4px; white-space: pre-wrap;">${text}</p>

        <h2>Analysis Results</h2>
        <div class="metric">
          <span class="label">Status:</span>
          <span class="${result.safe ? 'safe' : 'harmful'}">
            ${result.safe ? 'SAFE' : 'POTENTIALLY HARMFUL'}
          </span>
        </div>
        <div class="metric">
          <span class="label">Severity:</span>
          ${result.overallSeverity?.toUpperCase() || 'N/A'}
        </div>
        ${result.processingTime ? `
        <div class="metric">
          <span class="label">Processing Time:</span>
          ${result.processingTime}ms
        </div>
        ` : ''}

        ${result.detectedLanguage ? `
        <h2>Language Detection</h2>
        <p><strong>Primary Language:</strong> ${result.detectedLanguage.primary}</p>
        <p><strong>Confidence:</strong> ${Math.round(result.detectedLanguage.confidence * 100)}%</p>
        <p><strong>Code-Mixed:</strong> ${result.detectedLanguage.isCodeMixed ? 'Yes' : 'No'}</p>
        ` : ''}

        ${result.categories && result.categories.length > 0 ? `
        <h2>Category Breakdown</h2>
        <table>
          <thead>
            <tr>
              <th>Category</th>
              <th>Confidence</th>
              <th>Severity</th>
            </tr>
          </thead>
          <tbody>
            ${result.categories.map((cat: any) => `
              <tr>
                <td>${cat.name}</td>
                <td>${Math.round(cat.confidence * 100)}%</td>
                <td>${cat.severity.toUpperCase()}</td>
              </tr>
            `).join('')}
          </tbody>
        </table>
        ` : ''}

        <h2>Explanation</h2>
        <p>${result.explanation || 'No explanation provided.'}</p>

        ${result.suggestions ? `
        <h2>Suggestions</h2>
        <p>${result.suggestions}</p>
        ` : ''}

        ${result.attentionWeights && result.attentionWeights.length > 0 ? `
        <h2>Top Attention Words</h2>
        <table>
          <thead>
            <tr>
              <th>Word</th>
              <th>Weight</th>
            </tr>
          </thead>
          <tbody>
            ${result.attentionWeights.slice(0, 10).map((w: any) => `
              <tr>
                <td>${w.word}</td>
                <td>${Math.round(w.weight * 100)}%</td>
              </tr>
            `).join('')}
          </tbody>
        </table>
        ` : ''}

        <div class="footer">
          <p>This report was generated by the AI Safety Platform.</p>
          <p>Model: BiLSTM + Self-Attention Mechanism + Category-Focused Classification Layer Framework</p>
        </div>
      </body>
      </html>
    `;

    // Create blob and download
    const blob = new Blob([htmlContent], { type: 'text/html' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `analysis-report-${Date.now()}.html`;
    a.click();
    window.URL.revokeObjectURL(url);

    toast({
      title: "Report exported",
      description: "Analysis report downloaded as HTML (open in browser to print as PDF)",
    });
  };

  return (
    <Button variant="outline" size="sm" onClick={exportToPDF}>
      <Download className="w-4 h-4 mr-2" />
      Export Report
    </Button>
  );
};
